SwapServer = "http://127.0.0.1:11556"

Account = "boom"

BridgeConfigFile = "/Users/boom/bitmain/projects/crosschain/antpool/CrossChain-Bridge/test-conf/dcrn/config.toml"

TokenConfigFile = "/Users/boom/bitmain/projects/crosschain/antpool/CrossChain-Bridge/test-conf/dcrn/tokenpairs/config-tokenpair-example.toml"