PairID = "DCRN"
DiffDecimals = false

# source token config
[SrcToken]
# ID must be ERC20 if source token is erc20 token
ID = "DCRN"
Name = "DCRN"
Symbol = "DCRN"
Decimals = 8
Description = "DCRN Coin"
# if ID is ERC20, this is the erc20 token's contract address
ContractAddress = ""
# deposit to this address to make swap
DepositAddress = "ScuM2dPdzioAoHuQry3tPcFJ5d7AVsakTbK"
# dcrm
DcrmAddressPriKey = "PsUQPn498jvZCXboqxdXD8MjQqQunWCiiHywt3XrNR3A7FzsDpwof"
# withdraw from this address
DcrmAddress = "ScuM2dPdzioAoHuQry3tPcFJ5d7AVsakTbK"
# dcrm address public key
DcrmPubkey = ""
# maximum deposit value
MaximumSwap = 1000000.0
# minimum deposit value
MinimumSwap = 0.2
# calced deposit fee = deposit value * this rate (when in [min, max] deposit fee range)
SwapFeeRate = 0.001
# maximum deposit fee, if calced deposit fee is larger than this fee, then use this value as deposit fee
MaximumSwapFee = 50.0
# minimum deposit fee, if calced deposit fee is smaller than this fee, then use this value as deposit fee
MinimumSwapFee = 0.05
# plus this percentage of gas price to make tx more easier to be mined in source chain
# corresponding to send asset on source chain (eg. BTC) for withdrawing
PlusGasPricePercentage = 15 # plus 15% gas price
# if deposit value is larger than this value then need more verify strategy
BigValueThreshold = 500000.0
# disable deposit function if this flag is true
DisableSwap = false
# default gas limit
DefaultGasLimit = 90000
# allow swapin from contract address
AllowSwapinFromContract = false
# big value whitelist
BigValueWhitelist = [
	"0x1111111111111111111111111111111111111111",
	"0x2222222222222222222222222222222222222222"
]

# dest token config
[DestToken]
ID = "bDCRN"
Name = "bDCRN"
Symbol = "bDCRN"
Decimals = 8
Description = "cross chain bridge DCRN with DCRN"
# mapping erc20 token address
ContractAddress = "0xc5D9da57549A143a52F98107A73eaf9108B1111c"

# mapping erc20 token creator
DcrmAddress = "0x040C22254EE46d612978496283d2565e39b817e0"
# priky  as DCRM
DcrmAddressPriKey = "47f909f570c10408b254ca6c11f0935fb65e0f2379e752ddfccd9a475691e43e"

# dcrm address public key
DcrmPubkey = "04c1d78f946714f3573bf9f3596a9f8e2bc6f423ea1f37fede76e2da914134e3e699aa820a2e3fc64a1e0c5b11914c9338b7ae046fdbf76841521972bdf16e79bb"
# maximum withdraw value
MaximumSwap = 1000000.0
# minimum withdraw value
MinimumSwap = 0.2
# calced withdraw fee = withdraw value * this rate (when in [min, max] withdraw fee range)
SwapFeeRate = 0.001
# maximum withdraw fee, if calced withdraw fee is larger than this fee, then use this value as withdraw fee
MaximumSwapFee = 50.0
# minimum withdraw fee, if calced withdraw fee is smaller than this fee, then use this value as withdraw fee
MinimumSwapFee = 0.05
# plus this percentage of gas price to make tx more easier to be mined in dest chain
# corresponding to send mapping token on dest chain (eg. mBTC) for depositing
PlusGasPricePercentage = 15 # plus 1% gas price
# if withdraw value is larger than this value then need more verify strategy
BigValueThreshold = 500000.0
# disable withdraw function if this flag is true
DisableSwap = false
# default gas limit
DefaultGasLimit = 90000
# allow swapout from contract address
AllowSwapoutFromContract = false
# big value whitelist
BigValueWhitelist = [
	"0x1111111111111111111111111111111111111111",
	"0x2222222222222222222222222222222222222222"
]
