PairID = "DCRN"
DiffDecimals = false

# source token config
[SrcToken]
# ID must be ERC20 if source token is erc20 token
ID = "DCRN"
Name = "DCRN"
Symbol = "DCRN"
Decimals = 8
Description = "DCRN Coin"
# if ID is ERC20, this is the erc20 token's contract address
ContractAddress = ""
# deposit to this address to make swap
DepositAddress = "SsWzo3muBogW2aipZsJyKkPqdPyxmBWLzjn"
# account4 as dcrm
DcrmAddressPriKey = "PsUR4C4jopKuKy64WYiFE31KQPLPp5chkCDUJDeWuxFpLtLjZgAfG"

# withdraw from this address
DcrmAddress = "SspNRQnRCL88JYoNhEgnchbLpiaYCj682id"
# dcrm address public key
DcrmPubkey = ""
# maximum deposit value
MaximumSwap = 1000.0
# minimum deposit value
MinimumSwap = 0.00001
# calced deposit fee = deposit value * this rate (when in [min, max] deposit fee range)
SwapFeeRate = 0.001
# maximum deposit fee, if calced deposit fee is larger than this fee, then use this value as deposit fee
MaximumSwapFee = 0.01
# minimum deposit fee, if calced deposit fee is smaller than this fee, then use this value as deposit fee
MinimumSwapFee = 0.00001
# plus this percentage of gas price to make tx more easier to be mined in source chain
# corresponding to send asset on source chain (eg. BTC) for withdrawing
PlusGasPricePercentage = 15 # plus 15% gas price
# if deposit value is larger than this value then need more verify strategy
BigValueThreshold = 50000.0
# disable deposit function if this flag is true
DisableSwap = false
# default gas limit
DefaultGasLimit = 90000
# allow swapin from contract address
AllowSwapinFromContract = false
# big value whitelist
BigValueWhitelist = [
	"0x1111111111111111111111111111111111111111",
	"0x2222222222222222222222222222222222222222"
]

# dest token config
[DestToken]
ID = "mDCRN"
Name = "mDCRN"
Symbol = "mDCRN"
Decimals = 8
Description = "cross chain bridge BTC with mBTC"
# mapping erc20 token address
ContractAddress = "0xd2656eA85A91556E08AcF3Fb1f19b940967cBa20"
# mapping erc20 token creator
DcrmAddress = "0x30542709eaEA5Db50bFD00B00FCcA150192c5a60"

# mutichain2 priky  as DCRM
DcrmAddressPriKey = "1ffa05c8f791460d868c8fbc71496f1a7c2a10cc0a3063554b12849c22a2955e"

# dcrm address public key
DcrmPubkey = "04c1d78f946714f3573bf9f3596a9f8e2bc6f423ea1f37fede76e2da914134e3e699aa820a2e3fc64a1e0c5b11914c9338b7ae046fdbf76841521972bdf16e79bb"
# maximum withdraw value
MaximumSwap = 100.0
# minimum withdraw value
MinimumSwap = 0.00001
# calced withdraw fee = withdraw value * this rate (when in [min, max] withdraw fee range)
SwapFeeRate = 0.001
# maximum withdraw fee, if calced withdraw fee is larger than this fee, then use this value as withdraw fee
MaximumSwapFee = 0.01
# minimum withdraw fee, if calced withdraw fee is smaller than this fee, then use this value as withdraw fee
MinimumSwapFee = 0.00001
# plus this percentage of gas price to make tx more easier to be mined in dest chain
# corresponding to send mapping token on dest chain (eg. mBTC) for depositing
PlusGasPricePercentage = 1 # plus 1% gas price
# if withdraw value is larger than this value then need more verify strategy
BigValueThreshold = 50.0
# disable withdraw function if this flag is true
DisableSwap = false
# default gas limit
DefaultGasLimit = 90000
# allow swapout from contract address
AllowSwapoutFromContract = false
# big value whitelist
BigValueWhitelist = [
	"0x1111111111111111111111111111111111111111",
	"0x2222222222222222222222222222222222222222"
]
